# Generated by Django 4.1.2 on 2023-01-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_cart_fooditem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
