# Generated by Django 4.1.2 on 2023-01-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fooditem',
        ),
    ]
