# Generated by Django 4.1.2 on 2023-02-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Tax'},
        ),
    ]
