# Generated by Django 4.1.2 on 2023-02-25 10:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
