# Generated by Django 4.1.2 on 2023-02-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_data',
        ),
    ]
